# Generated by Django 4.2.5 on 2023-10-05 11:54

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_issue_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='id_comment',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
    ]
